### ISSUE TITLE
Shadow Mapping Demo

### ISSUE THREAD

**Issue by philmaker1** [xeolabs/xeoengine#15] opened 2015-12-31 02:58 UTC
This was not a priority for SceneJS architecturally and it's probably not a priority for xeoEngine. Consider creating a basic shadow mapping demo for xeoEngine.

**Comment by xeolabs** [comment] 2016-08-08 10:12
Duplicate of https://github.com/xeolabs/xeoengine/issues/54

**Closed by xeolabs** 2016-08-08 10:12 UTC
